### ISSUE TITLE
Unable to select Fivetran connection in the Airflow Dashboard

### ISSUE THREAD

**Issue by fivetran-edkoo** [astronomer/airflow-provider-fivetran-async#90] opened 2024-04-26 23:26 UTC
My customer is trying to create a connection in the Astronomer Dashboard but is not able to see the Fivetran option.

![image](https://github.com/astronomer/airflow-provider-fivetran-async/assets/78041839/f8929f9d-3ec5-4c5e-ad31-70c006a1e86f)

They are installing the packages for the fivetranoperation api calls but unable to get that in the creation of Dag,
airflow-provider-fivetran-async
airflow-provider-fivetran

They are referencing the following documents.
https://registry.astronomer.io/providers/airflow-provider-fivetran-async/versions/2.0.2/modules/FivetranOperator
https://docs.astronomer.io/learn/airflow-fivetran 

They are using Airflow MWAA in AWS with version 2.4.3

Can you help determine why the Fivetran option is not appearing? What configuration step are they missing?
Thank you!

**Comment by pankajastro** [comment] 2024-04-29 09:10
I attempted to replicate the issue using both airflow-2.4.3 and the latest version of the airflow main branch, but I was unable to do so. I observed that the option to select the Fivetran connection type is available in both scenarios.
<img width="1496" alt="Screenshot 2024-04-29 at 2 38 08 PM" src="https://github.com/astronomer/airflow-provider-fivetran-async/assets/98807258/3d9ea200-706f-4380-8d31-4f5c77b7d2ee">

**Comment by pankajastro** [comment] 2024-04-29 09:16
Could you please verify if the provider has been installed in your airflow environment? You can do this by navigating to the UI and selecting Admin -> Provider.

**Comment by fivetran-edkoo** [comment] 2024-04-29 20:05
I will ask my customer to check their Providers.

**Comment by fivetran-edkoo** [comment] 2024-04-30 23:46
My customer says that the installation of the Fivetran provider appeared to have succeeded based on the attached log files 

[requirements_install_ip_log-events-viewer-result.csv](https://github.com/astronomer/airflow-provider-fivetran-async/files/15172255/requirements_install_ip_log-events-viewer-result.csv)
[requirements.txt](https://github.com/astronomer/airflow-provider-fivetran-async/files/15172256/requirements.txt)

but the dashboard does not show the Fivetran provider.

![image](https://github.com/astronomer/airflow-provider-fivetran-async/assets/78041839/2c8705ad-8472-4626-a37a-001f9f417f6e)

Is there any other means to debug this situation in the Airflow dashboard? What other info do you require from my customer? Thank you.

**Comment by fivetran-edkoo** [comment] 2024-05-02 16:15
@pankajastro do you have any suggestions on how to debug this? Would it work if we schedule a conf call to review this with my customer? If so what are your working hours (in PT)? thx

**Comment by pankajastro** [comment] 2024-05-03 09:17
> do you have any suggestions on how to debug this?

The next step is to verify within your container/pod/machine whether files corresponding to this package actually exist

**Comment by pankajastro** [comment] 2024-05-03 09:25
> Would it work if we schedule a conf call to review this with my customer? If so what are your working hours (in PT)? thx

I believe the problem isn't linked to this package. As I previously mentioned, I tested it in Open Source Airflow. I'm inclined to think it's connected to your infrastructure. I recommend opening a support ticket with either AWS if you're using MWAA or with Astronomer if you're using Astro to know the root cause. 

Also, I would request you to check the related issue https://github.com/astronomer/airflow-provider-fivetran-async/issues/61 it has some suggestion which may help you.

**Comment by pankajkoti** [comment] 2024-05-03 09:26
Hello @fivetran-edkoo, this issue pertains specifically to MWAA (Managed Workflows for Apache Airflow) environments. It seems that MWAA deployments do not include Apache Airflow providers other than those already present in the base image. To resolve this, your customer will need to include the required provider in their requirements.txt file.

For example, they should add airflow-provider-fivetran-async==2.0.2 to their requirements.txt file. This process is akin to adding other Python dependencies to MWAA environments. You can find detailed steps outlined in the Amazon documentation here: [Installing Python dependencies](https://docs.aws.amazon.com/mwaa/latest/userguide/working-dags-dependencies.html).

Following this guide should help resolve the issue. If your customer encounters any further difficulties, they can open a support ticket for the Amazon MWAA team, who would have the necessary access to debug and provide assistance in such cases.

**Comment by phanikumv** [comment] 2024-05-10 06:38
Closing as this is not a Fivetran provider issue

**Closed by phanikumv** 2024-05-10 06:38 UTC
